name: Build Static Pages

on:
  workflow_dispatch:

#  push:
#    branches:
#      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10.0
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Site
        run: yarn build

      - name: Add Github files
        run: |
          touch build/.nojekyll
          echo tangym27.com >> build/CNAME

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build add --all
          git commit -m "Automatic Deploy action run by github-actions"
          git push origin HEAD:gh-pages --force
